name: mexa_ads
description: "A Google Admob plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: "5.3.1"
  uuid: "4.5.1"
  shimmer: "3.0.0"
  lottie: "3.0.0"
  visibility_detector: "0.4.0+2"
  adjust_sdk: "5.0.3"
  shared_preferences: "2.3.3"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - packages/mexa_ads/assets/loading.json
 
  plugin:
    platforms:
      android:
        package: com.mexa.mexa_ads
        pluginClass: MexaAdsPlugin
